/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOnPreferenceDialog: typeof import('./src/components/AddOnPreferenceDialog.vue')['default']
    AttendeeFormControl: typeof import('./src/components/AttendeeFormControl.vue')['default']
    BackButton: typeof import('./src/components/common/BackButton.vue')['default']
    BaseCustomEventForm: typeof import('./src/components/BaseCustomEventForm.vue')['default']
    BookingEventInfo: typeof import('./src/components/BookingEventInfo.vue')['default']
    BookingFinancialSummary: typeof import('./src/components/BookingFinancialSummary.vue')['default']
    BookingForm: typeof import('./src/components/BookingForm.vue')['default']
    BookingHeader: typeof import('./src/components/BookingHeader.vue')['default']
    BookingSummary: typeof import('./src/components/BookingSummary.vue')['default']
    BuzzLogo: typeof import('./src/components/common/BuzzLogo.vue')['default']
    CancellationRequestDialog: typeof import('./src/components/CancellationRequestDialog.vue')['default']
    CancellationRequestNotice: typeof import('./src/components/CancellationRequestNotice.vue')['default']
    CustomFieldInput: typeof import('./src/components/CustomFieldInput.vue')['default']
    CustomFieldsSection: typeof import('./src/components/CustomFieldsSection.vue')['default']
    EventDetailsHeader: typeof import('./src/components/EventDetailsHeader.vue')['default']
    EventSelector: typeof import('./src/components/EventSelector.vue')['default']
    EventSponsorForm: typeof import('./src/components/EventSponsorForm.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    LoginRequired: typeof import('./src/components/LoginRequired.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    OfflinePaymentDialog: typeof import('./src/components/OfflinePaymentDialog.vue')['default']
    PaymentGatewayDialog: typeof import('./src/components/PaymentGatewayDialog.vue')['default']
    PhoneInput: typeof import('./src/components/PhoneInput.vue')['default']
    ProfileView: typeof import('./src/components/ProfileView.vue')['default']
    ProposalEditDialog: typeof import('./src/components/ProposalEditDialog.vue')['default']
    QRCodeExpandDialog: typeof import('./src/components/QRCodeExpandDialog.vue')['default']
    QRScanner: typeof import('./src/components/QRScanner.vue')['default']
    RestrictionNotices: typeof import('./src/components/RestrictionNotices.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SponsorLogoUploader: typeof import('./src/components/SponsorLogoUploader.vue')['default']
    SponsorshipPaymentDialog: typeof import('./src/components/SponsorshipPaymentDialog.vue')['default']
    SuccessMessage: typeof import('./src/components/SuccessMessage.vue')['default']
    TicketCard: typeof import('./src/components/TicketCard.vue')['default']
    TicketDetailsModal: typeof import('./src/components/TicketDetailsModal.vue')['default']
    TicketsSection: typeof import('./src/components/TicketsSection.vue')['default']
    TicketTransferDialog: typeof import('./src/components/TicketTransferDialog.vue')['default']
    TransferTicketDialog: typeof import('./src/components/TransferTicketDialog.vue')['default']
  }
}
